services:
  app:
    container_name: admin_videos_app
    build:
      context: ../..
      dockerfile: Dockerfile.dev
#    image: kalilmvp/codeflix-admin-catalogo:main-4
    restart: no
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true
