name: CI Pipeline

on:
  push:

  # enable manual trigger through github actions interface
  workflow_dispatch:

jobs:
  # job to execute tests
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # configure job steps
    steps:
      # 1 - checkout source code
      - uses: actions/checkout@v3
      # 2 - configure JDK
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3 - configure JDK
      - name: Run application tests
        run: ./gradlew test


